project_id = "rrwhajzsghhybmpdejuo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.recognize-product]
verify_jwt = false
